In [ ]:
##########################################################################
# Federal University of Pernambuco - PIMES UFPE
# Research: The Impacts of Uncertainty on Economic Activity Across Brazilian States
# Researcher: Paulo Francisco da Silva Junior
# Advisor: Marcelo Eduardo Alves da Silva, PhD.
##########################################################################

In [2]:
# Import libraries
import pandas as pd
import numpy as np
#import yfinance as yf

In [3]:
# Variables to help loop interacion
estados = {
    "Bahia":"BA",
    "Ceará":"CE",
    "Espírito Santo":"ES",
    "Goiás":"GO",
    "Minas Gerais":"MG",
    "Pará":"PA",
    "Paraná":"PR",
    "Pernambuco":"PE",
    "Rio de Janeiro":"RJ",
    "Rio Grande do Sul":"RS",
    "Santa Catarina":"SC",
    "São Paulo":"SP"
}

main = pd.DataFrame({"UF":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27]})

In [4]:
# Read main data
PIB=pd.read_excel("Data\\Originais\\cross-section\\PIB Estadual - preços de mercado (preços de 2010).xls")
PIB.drop(columns=["Codigo","Estado"], inplace=True)
PIB.rename(columns={"Sigla":"UF",
                     "2016":"2016_PIB",
                     "2017":"2017_PIB",
                     "2018":"2018_PIB",
                     "2019":"2019_PIB"},inplace=True)

bem=pd.read_excel("Data\\Originais\\cross-section\\PIB Estadual (valor adicionado a preços básicos) - serviços - administração, defesa, saúde e educação públicas e seguridade social (preços de 2010).xls")
bem.drop(columns=["Codigo","Estado"], inplace=True)
bem.rename(columns={"Sigla":"UF",
                     "2016":"2016_Bem",
                     "2017":"2017_Bem",
                     "2018":"2018_Bem",
                     "2019":"2019_Bem"},inplace=True)


#san=pd.read_excel("Data\Originais\cross-section\PIB Estadual (valor adicionado a preços básicos) - indústria - serviços de eletricidade e gás, água, esgoto e limpeza urbana (preços de 2010).xls")
#san.drop(columns=["Codigo","Estado"], inplace=True)
#san.rename(columns={"Sigla":"UF",
#                     "2016":"2016_San",
#                     "2017":"2017_San",
#                     "2018":"2018_San",
#                     "2019":"2019_San"},inplace=True)

#cientifica=pd.read_excel("Data\\Originais\\cross-section\\PIB Estadual (valor adicionado a preços básicos) - serviços - atividades profissionais, científicas e técnicas, administrativas e serv. compl. (preços de 2010).xls")
#cientifica.drop(columns=["Codigo","Estado"], inplace=True)
#cientifica.rename(columns={"Sigla":"UF",
#                     "2016":"2016_Cien",
#                     "2017":"2017_Cien",
#                     "2018":"2018_Cien",
#                     "2019":"2019_Cien"},inplace=True)


agro=pd.read_excel("Data\\Originais\\cross-section\\PIB Estadual (valor adicionado a preços básicos) - agropecuária (preços de 2010).xls")
agro.drop(columns=["Codigo","Estado"], inplace=True)
agro.rename(columns={"Sigla":"UF",
                     "2016":"2016_Agro",
                     "2017":"2017_Agro",
                     "2018":"2018_Agro",
                     "2019":"2019_Agro"},inplace=True)

construcao=pd.read_excel("Data\\Originais\\cross-section\\PIB Estadual (valor adicionado a preços básicos) - indústria - construção civil (preços de 2010).xls")
construcao.drop(columns=["Codigo","Estado"], inplace=True)
construcao.rename(columns={"Sigla":"UF",
                           "2016":"2016_Const",
                           "2017":"2017_Const",
                           "2018":"2018_Const",
                           "2019":"2019_Const"},inplace=True)

extrativa=pd.read_excel("Data\\Originais\\cross-section\\PIB Estadual (valor adicionado a preços básicos) - indústria - extrativa (preços de 2010).xls")
extrativa.drop(columns=["Codigo","Estado"], inplace=True)
extrativa.rename(columns={"Sigla":"UF",
                          "2016":"2016_Extr",
                          "2017":"2017_Extr",
                          "2018":"2018_Extr",
                          "2019":"2019_Extr"},inplace=True)

transformacao=pd.read_excel("Data\\Originais\\cross-section\\PIB Estadual (valor adicionado a preços básicos) - indústria - transformação (preços de 2010).xls")
transformacao.drop(columns=["Codigo","Estado"], inplace=True)
transformacao.rename(columns={"Sigla":"UF",
                              "2016":"2016_Transf",
                              "2017":"2017_Transf",
                              "2018":"2018_Transf",
                              "2019":"2019_Transf"},inplace=True)

financas=pd.read_excel("Data\Originais\cross-section\PIB Estadual (valor adicionado a preços básicos) - serviços - atividades financeiras, de seguros e serviços relacionados (preços de 2010).xls")
financas.drop(columns=["Codigo","Estado"], inplace=True)
financas.rename(columns={"Sigla":"UF",
                     "2016":"2016_Fin",
                     "2017":"2017_Fin",
                     "2018":"2018_Fin",
                     "2019":"2019_Fin"},inplace=True)

dados = pd.read_excel("Data\\Originais\\cross-section\\Despesa corrente - empenhada - estadual.xls")
dados.rename(columns={"Sigla":"UF",
                     "2016":"2016_Desp",
                     "2017":"2017_Desp",
                     "2018":"2018_Desp",
                     "2019":"2019_Desp"},inplace=True)
dados.drop(columns=["Codigo","Estado"],inplace=True)

<>:68: SyntaxWarning: invalid escape sequence '\O'
<>:68: SyntaxWarning: invalid escape sequence '\O'
C:\Users\Paulo\AppData\Local\Temp\ipykernel_18992\2056439456.py:68: SyntaxWarning: invalid escape sequence '\O'
  financas=pd.read_excel("Data\Originais\cross-section\PIB Estadual (valor adicionado a preços básicos) - serviços - atividades financeiras, de seguros e serviços relacionados (preços de 2010).xls")

In [5]:
# Adjust Public debt
divpub = pd.read_csv("Data\\Originais\\cross-section\\Divida-Consolidada-dos-Estados---PAF.csv", sep=";", decimal=",")
divpub = divpub[(divpub["UF"].isin(list(estados.values()))) & ((divpub["ANO"]>=2016) & (divpub["ANO"]<=2019))]
divpub.reset_index(drop=True, inplace=True)
divpub["VALOR"] = divpub["VALOR"].str.replace(".","")
divpub["VALOR"] = divpub["VALOR"].str.replace(",",".").astype(float)
divpub["VALOR"] = divpub["VALOR"]/1000
divpub["DivPub"]=np.nan

In [6]:
# Calculate percentage
for uf in list(estados.values()):
    divpub.loc[divpub["UF"]==uf, "DivPub"] = (divpub[(divpub["ANO"]==2016) & (divpub["UF"]==uf)]["VALOR"].values[0]/PIB[PIB["UF"]==uf]["2016_PIB"].values[0] +
        divpub[(divpub["ANO"]==2017) & (divpub["UF"]==uf)]["VALOR"].values[0]/PIB[PIB["UF"]==uf]["2017_PIB"].values[0] +
        divpub[(divpub["ANO"]==2018) & (divpub["UF"]==uf)]["VALOR"].values[0]/PIB[PIB["UF"]==uf]["2018_PIB"].values[0] +
        divpub[(divpub["ANO"]==2019) & (divpub["UF"]==uf)]["VALOR"].values[0]/PIB[PIB["UF"]==uf]["2019_PIB"].values[0])/4

In [7]:
# Final changes
divpub.drop_duplicates(subset="UF", keep='first', inplace=True)
divpub.drop(columns=["ANO","VALOR"],inplace=True)
divpub.reset_index(drop=True,inplace=True)

In [ ]:
# Check out the results
divpub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   UF      12 non-null     object
 1   DivPub  12 non-null     float64
dtypes: float64(1), object(1)
memory usage: 324.0+ bytes

In [9]:
# Obtain all states
main["UF"]=PIB["UF"].to_list()

In [10]:
# Merges
main = pd.merge(main,PIB,on="UF",how="outer")
main = pd.merge(main,agro,on="UF",how="outer")
main = pd.merge(main,construcao,on="UF",how="outer")
main = pd.merge(main,extrativa,on="UF",how="outer")
main = pd.merge(main,transformacao,on="UF",how="outer")
main = pd.merge(main,financas,on="UF",how="outer")
main = pd.merge(main,divpub,on="UF",how="outer")
main = pd.merge(main,bem,on="UF",how="outer")

main = pd.merge(main,dados,on="UF",how="outer") #orçamento
#main = pd.merge(main,cientifica,on="UF",how="outer")
#main = pd.merge(main,san,on="UF",how="outer")

In [11]:
main

,UF,2016_PIB,2017_PIB,2018_PIB,2019_PIB,2016_Agro,2017_Agro,2018_Agro,2019_Agro,2016_Const,...,2019_Fin,DivPub,2016_Bem,2017_Bem,2018_Bem,2019_Bem,2016_Desp,2017_Desp,2018_Desp,2019_Desp
0,AC,8.725471e+06,8.733873e+06,8.977966e+06,8.782024e+06,9.247506e+05,8.213087e+05,7.095160e+05,5.871296e+05,3.632690e+05,...,2.663017e+05,NaN,3.095236e+06,3.175912e+06,3.195764e+06,3.187989e+06,4.829741e+09,5.421346e+09,5.913768e+09,5.877614e+09
1,AL,3.138218e+07,3.234053e+07,3.186449e+07,3.312990e+07,4.283424e+06,5.197034e+06,4.758060e+06,5.315222e+06,1.459544e+06,...,1.024636e+06,NaN,7.549671e+06,7.574373e+06,7.653016e+06,7.546808e+06,9.135466e+09,9.521908e+09,9.047833e+09,8.156535e+09
2,AM,5.648542e+07,5.705537e+07,5.862436e+07,6.078361e+07,3.730174e+06,3.429211e+06,3.229546e+06,2.792752e+06,2.216941e+06,...,1.130622e+06,NaN,9.644699e+06,9.989447e+06,1.019298e+07,1.077622e+07,1.366167e+10,1.407026e+10,1.581077e+10,1.768845e+10
3,AP,9.098423e+06,9.473662e+06,9.835339e+06,9.830833e+06,1.836460e+05,1.902460e+05,1.721740e+05,1.749256e+05,4.768975e+05,...,2.051957e+05,NaN,3.946402e+06,4.090831e+06,4.210474e+06,4.390967e+06,3.836120e+09,3.882546e+09,4.340897e+09,4.699522e+09
4,BA,1.641399e+08,1.644372e+08,1.676230e+08,1.647628e+08,1.048879e+07,9.684740e+06,1.118264e+07,9.826033e+06,9.365402e+06,...,5.338052e+06,0.142222,2.953501e+07,3.009794e+07,2.995182e+07,3.122565e+07,3.848171e+10,4.192169e+10,4.278599e+10,4.504297e+10
5,CE,8.781305e+07,9.051588e+07,9.129789e+07,9.190792e+07,3.628913e+06,4.581810e+06,4.153276e+06,4.135406e+06,5.410118e+06,...,3.388788e+06,0.142414,1.803083e+07,1.885342e+07,1.900039e+07,1.928450e+07,2.001605e+10,2.095211e+10,2.308388e+10,2.441819e+10
6,DF,1.494229e+08,1.497500e+08,1.492220e+08,1.537351e+08,5.206739e+05,5.068604e+05,5.988919e+05,5.575955e+05,3.604625e+06,...,2.262897e+07,NaN,5.839598e+07,5.996957e+07,5.961029e+07,6.024318e+07,2.542633e+10,2.073047e+10,2.335102e+10,2.359410e+10
7,ES,6.931561e+07,6.939149e+07,8.023948e+07,7.717025e+07,2.707969e+06,2.745933e+06,2.566802e+06,2.332819e+06,2.877465e+06,...,2.815006e+06,0.092903,1.038395e+07,1.017993e+07,1.038081e+07,1.064847e+07,1.278266e+10,1.312672e+10,1.430762e+10,1.495682e+10
8,GO,1.153054e+08,1.174567e+08,1.145920e+08,1.172466e+08,1.251495e+07,1.188530e+07,1.165667e+07,1.189832e+07,6.543923e+06,...,4.648596e+06,0.171402,1.625612e+07,1.755379e+07,1.775343e+07,1.885380e+07,1.979173e+10,2.159765e+10,2.336389e+10,2.779327e+10
9,MA,5.411933e+07,5.479285e+07,5.749430e+07,5.469230e+07,3.836793e+06,4.594685e+06,4.555288e+06,4.114217e+06,3.177980e+06,...,1.473620e+06,NaN,1.304201e+07,1.333692e+07,1.375445e+07,1.387113e+07,1.413646e+10,1.542056e+10,1.687362e+10,1.500284e+10
10,MG,3.456191e+08,3.526947e+08,3.600737e+08,3.662671e+08,2.107158e+07,1.756909e+07,1.642517e+07,1.483470e+07,1.689403e+07,...,1.464170e+07,0.331060,5.335588e+07,5.512131e+07,5.461229e+07,5.410902e+07,8.354847e+10,9.302619e+10,9.811016e+10,1.016866e+11
11,MS,5.829501e+07,5.898674e+07,6.264155e+07,6.008811e+07,1.009999e+07,9.300838e+06,1.071448e+07,9.139463e+06,2.836675e+06,...,1.878778e+06,NaN,9.690636e+06,1.022865e+07,1.049238e+07,1.099535e+07,1.094882e+10,1.308244e+10,1.311537e+10,1.376524e+10
12,MT,7.858769e+07,7.761932e+07,8.048707e+07,7.985398e+07,1.591237e+07,1.378599e+07,1.504071e+07,1.519913e+07,3.706773e+06,...,2.635777e+06,NaN,1.197368e+07,1.218467e+07,1.245498e+07,1.236220e+07,1.522328e+10,1.607402e+10,1.718475e+10,1.744960e+10
13,PA,8.761321e+07,9.498954e+07,9.448696e+07,1.002245e+08,1.089109e+07,1.024546e+07,8.765234e+06,8.396793e+06,4.524575e+06,...,2.093619e+06,0.041459,1.786963e+07,1.895901e+07,1.898372e+07,1.936670e+07,1.998300e+10,2.091213e+10,2.255258e+10,2.409489e+10
14,PB,3.749513e+07,3.818173e+07,3.769743e+07,3.819928e+07,1.377088e+06,1.319427e+06,1.325736e+06,1.233697e+06,1.851944e+06,...,1.360289e+06,NaN,1.113499e+07,1.148085e+07,1.125931e+07,1.122184e+07,8.748729e+09,9.025691e+09,9.596085e+09,9.943037e+09
15,PE,1.061610e+08,1.111302e+08,1.091284e+08,1.111677e+08,3.927318e+06,3.693775e+06,3.919718e+06,4.243025e+06,4.778598e+06,...,3.853189e+06,0.140269,2.198212e+07,2.328723e+07,2.338241e+07,2.369483e+07,2.784268e+10,3.085105e+10,3.240772e+10,3.503221e+10
16,PI,2.627425e+07,2.776000e+07,2.950180e+07,2.965589e+07,1.185227e+06,2.320164e+06,2.599040e+06,2.120154e+06,1.620831e+06,...,9.671403e+05,NaN,1.304201e+07,1.333692e+07,1.375445e+07,1.387113e+07,7.990320e+09,8.423523e+09,9.420054e+09,1.135645e+10
17,PR,2.549045e+08,2.579222e+08,2.576829e+08,2.620429e+08,2.199438e+07,2.108322e+07,2.129547e+07,1.929307e+07,1.119446e+07,...,1.029966e+07,0.093848,3.111895e+07,3.213948e+07,3.103238e+07,3.092240e+07,4.680694e+10,5.123938e+10,4.696545e+10,4.775302e+10
18,RJ,4.062603e+08,4.109678e+08,4.443908e+08,4.382174e+08,1.952051e+06,1.790482e+06,1.737309e+06,1.703177e+06,1.852543e+07,...,1.790128e+07,0.340555,7.522504e+07,7.458284e+07,7.363476e+07,7.524316e+07,5.614279e+10,6.603672e+10,6.465848e+10,6.487027e+10
19,RN,3.785839e+07,3.935001e+07,3.921764e+07,4.008193e+07,1.183829e+06,1.322091e+06,1.520679e+06,1.513705e+06,2.106919e+06,...,1.248897e+06,NaN,1.002444e+07,1.040881e+07,1.023567e+07,1.064886e+07,9.145253e+09,1.032906e+10,9.292788e+09,1.228043e+10
20,RO,2.503302e+07,2.662832e+07,2.630180e+07,2.645917e+07,3.117723e+06,3.596111e+06,3.356517e+06,3.288515e+06,1.086804e+06,...,7.519305e+05,NaN,6.275856e+06,6.584230e+06,6.665609e+06,6.610706e+06,5.821437e+09,6.424629e+09,6.632663e+09,6.945001e+09
21,RR,6.986623e+06,7.407092e+06,7.829517e+06,8.030361e+06,3.577286e+05,3.727433e+05,3.752737e+05,4.034344e+05,4.174392e+05,...,2.209729e+05,NaN,3.172190e+06,3.385030e+06,3.310867e+06,3.479671e+06,3.095901e+09,3.528315e+09,2.952162e+09,3.522399e+09
22,RS,2.593296e+08,2.590067e+08,2.677931e+08,2.710817e+08,2.300882e+07,2.056794e+07,2.084320e+07,2.037566e+07,1.071048e+07,...,1.371711e+07,0.306503,3.219120e+07,3.256578e+07,3.356848e+07,3.492639e+07,5.524966e+10,6.041050e+10,6.620490e+10,7.132110e+10
23,SC,1.628811e+08,1.696667e+08,1.746430e+08,1.816320e+08,9.518734e+06,8.696708e+06,8.005885e+06,8.543018e+06,8.018050e+06,...,5.829988e+06,0.134981,1.994069e+07,2.060595e+07,2.077805e+07,2.117277e+07,2.169867e+10,2.307549e+10,2.460222e+10,2.579886e+10
24,SE,2.466323e+07,2.491210e+07,2.460589e+07,2.510964e+07,1.094433e+06,1.203237e+06,8.317280e+05,1.144891e+06,1.727122e+06,...,1.041274e+06,NaN,6.257834e+06,6.433265e+06,6.345185e+06,6.646526e+06,7.138760e+09,7.881639e+09,8.115886e+09,8.947358e+09
25,SP,1.293355e+09,1.297733e+09,1.294514e+09,1.319459e+09,2.272850e+07,2.234395e+07,1.851542e+07,1.858367e+07,4.825438e+07,...,1.365859e+08,0.230234,1.057349e+08,1.059318e+08,1.051430e+08,1.048367e+08,2.015336e+11,2.128869e+11,2.233887e+11,2.394636e+11
26,TO,2.003691e+07,2.087139e+07,2.088626e+07,2.211289e+07,2.296113e+06,2.545126e+06,2.454978e+06,2.830081e+06,8.235863e+05,...,6.766032e+05,NaN,5.731015e+06,5.587270e+06,5.858431e+06,6.152382e+06,7.680680e+09,8.054942e+09,7.673717e+09,8.309965e+09

In [12]:
# calculate percents
main["Bem"]=(
(main["2016_Bem"]/main["2016_PIB"])+
(main["2017_Bem"]/main["2017_PIB"])+
(main["2018_Bem"]/main["2018_PIB"])+
(main["2019_Bem"]/main["2019_PIB"]))/4

main["Agro"]=(
(main["2016_Agro"]/main["2016_PIB"])+
(main["2017_Agro"]/main["2017_PIB"])+
(main["2018_Agro"]/main["2018_PIB"])+
(main["2019_Agro"]/main["2019_PIB"]))/4

main["Construcao"]=(
(main["2016_Const"]/main["2016_PIB"])+
(main["2017_Const"]/main["2017_PIB"])+
(main["2018_Const"]/main["2018_PIB"])+
(main["2019_Const"]/main["2019_PIB"]))/4

main["Extrativa"]=(
(main["2016_Extr"]/main["2016_PIB"])+
(main["2017_Extr"]/main["2017_PIB"])+
(main["2018_Extr"]/main["2018_PIB"])+
(main["2019_Extr"]/main["2019_PIB"]))/4

main["Transformacao"]=(
(main["2016_Transf"]/main["2016_PIB"])+
(main["2017_Transf"]/main["2017_PIB"])+
(main["2018_Transf"]/main["2018_PIB"])+
(main["2019_Transf"]/main["2019_PIB"]))/4

main["financas"]=(
(main["2016_Fin"]/main["2016_PIB"])+
(main["2017_Fin"]/main["2017_PIB"])+
(main["2018_Fin"]/main["2018_PIB"])+
(main["2019_Fin"]/main["2019_PIB"]))/4

main["state_expenditure_pib"]=(
((main["2016_Desp"]/1000)/main["2016_PIB"])+
((main["2017_Desp"]/1000)/main["2017_PIB"])+
((main["2018_Desp"]/1000)/main["2018_PIB"])+
((main["2019_Desp"]/1000)/main["2019_PIB"]))/4

#main["Bem_final"]=(
#((main["2016_San"]+main["2016_Bem"])/main["2016_PIB"])+
#((main["2017_San"]+main["2017_Bem"])/main["2017_PIB"])+
#((main["2018_San"]+main["2018_Bem"])/main["2018_PIB"])+
#((main["2019_San"]+main["2019_Bem"])/main["2019_PIB"]))/4

#main["Saneamento"]=(
#(main["2016_San"]/main["2016_PIB"])+
#(main["2017_San"]/main["2017_PIB"])+
#(main["2018_San"]/main["2018_PIB"])+
#(main["2019_San"]/main["2019_PIB"]))/4

#main["Cientifica"]=(
#(main["2016_Cien"]/main["2016_PIB"])+
#(main["2017_Cien"]/main["2017_PIB"])+
#(main["2018_Cien"]/main["2018_PIB"])+
#(main["2019_Cien"]/main["2019_PIB"]))/4

In [ ]:
# Check out the results
main.head()

,UF,2016_PIB,2017_PIB,2018_PIB,2019_PIB,2016_Agro,2017_Agro,2018_Agro,2019_Agro,2016_Const,...,2017_Desp,2018_Desp,2019_Desp,Bem,Agro,Construcao,Extrativa,Transformacao,financas,state_expenditure_pib
0,AC,8.725471e+06,8.733873e+06,8.977966e+06,8.782024e+06,9.247506e+05,8.213087e+05,7.095160e+05,5.871296e+05,3.632690e+05,...,5.421346e+09,5.913768e+09,5.877614e+09,0.359334,0.086476,0.036266,0.000211,0.021182,0.030446,0.625556
1,AL,3.138218e+07,3.234053e+07,3.186449e+07,3.312990e+07,4.283424e+06,5.197034e+06,4.758060e+06,5.315222e+06,1.459544e+06,...,9.521908e+09,9.047833e+09,8.156535e+09,0.235687,0.151737,0.039013,0.003142,0.047956,0.029844,0.278919
2,AM,5.648542e+07,5.705537e+07,5.862436e+07,6.078361e+07,3.730174e+06,3.429211e+06,3.229546e+06,2.792752e+06,2.216941e+06,...,1.407026e+10,1.581077e+10,1.768845e+10,0.174247,0.056794,0.032002,0.009336,0.223092,0.017755,0.262293
3,AP,9.098423e+06,9.473662e+06,9.835339e+06,9.830833e+06,1.836460e+05,1.902460e+05,1.721740e+05,1.749256e+05,4.768975e+05,...,3.882546e+09,4.340897e+09,4.699522e+09,0.435076,0.018891,0.040182,0.001391,0.018924,0.021623,0.437712
4,BA,1.641399e+08,1.644372e+08,1.676230e+08,1.647628e+08,1.048879e+07,9.684740e+06,1.118264e+07,9.826033e+06,9.365402e+06,...,4.192169e+10,4.278599e+10,4.504297e+10,0.182795,0.062287,0.048139,0.008623,0.108648,0.032481,0.254504

In [14]:
# Filter
main=main[["UF","Bem","Agro","Construcao","Extrativa","Transformacao","financas","DivPub", "state_expenditure_pib"]]
#"Cientifica" ,"Saneamento","Bem_final"

In [15]:
main

,UF,Bem,Agro,Construcao,Extrativa,Transformacao,financas,DivPub,state_expenditure_pib
0,AC,0.359334,0.086476,0.036266,0.000211,0.021182,0.030446,NaN,0.625556
1,AL,0.235687,0.151737,0.039013,0.003142,0.047956,0.029844,NaN,0.278919
2,AM,0.174247,0.056794,0.032002,0.009336,0.223092,0.017755,NaN,0.262293
3,AP,0.435076,0.018891,0.040182,0.001391,0.018924,0.021623,NaN,0.437712
4,BA,0.182795,0.062287,0.048139,0.008623,0.108648,0.032481,0.142222,0.254504
5,CE,0.207890,0.045608,0.045136,0.002286,0.076003,0.038262,0.142414,0.244484
6,DF,0.395653,0.003627,0.019899,0.000077,0.009306,0.144725,NaN,0.154639
7,ES,0.140967,0.035214,0.037281,0.075188,0.088425,0.035289,0.092903,0.186427
8,GO,0.151541,0.103233,0.050037,0.005501,0.103399,0.040765,0.171402,0.199115
9,MA,0.244311,0.077301,0.046749,0.005751,0.057998,0.025193,NaN,0.277610
10,MG,0.152516,0.049225,0.042647,0.036676,0.122159,0.040309,0.331060,0.263899
11,MS,0.172532,0.163520,0.041548,0.003208,0.105928,0.029863,NaN,0.212015
12,MT,0.154724,0.189324,0.041748,0.003039,0.070813,0.031234,NaN,0.208207
13,PA,0.199424,0.102179,0.044781,0.130209,0.040579,0.020320,0.041459,0.231832
14,PB,0.297527,0.034687,0.046502,0.002396,0.056977,0.033779,NaN,0.246142
15,PE,0.211006,0.036080,0.037701,0.000655,0.107437,0.035859,0.140269,0.287995
16,PI,0.477694,0.072070,0.053834,0.001316,0.030000,0.031023,NaN,0.327450
17,PR,0.121281,0.081074,0.038991,0.001251,0.138013,0.039795,0.093848,0.186695
18,RJ,0.176012,0.004239,0.034841,0.067150,0.055101,0.044472,0.340555,0.148103
19,RN,0.263995,0.035352,0.044438,0.020707,0.060120,0.030634,NaN,0.261849
20,RO,0.250310,0.127874,0.035388,0.001810,0.049687,0.027492,NaN,0.247119
21,RR,0.441805,0.049923,0.051857,0.001232,0.012282,0.028863,NaN,0.433788
22,RS,0.126015,0.080283,0.036419,0.000960,0.139078,0.049479,0.306503,0.239152
23,SC,0.119855,0.050643,0.041845,0.002349,0.164238,0.033113,0.134981,0.138033
24,SE,0.258636,0.043018,0.051219,0.013071,0.052721,0.040009,NaN,0.322999
25,SP,0.081014,0.015795,0.032552,0.004192,0.125855,0.107320,0.230234,0.168480
26,TO,0.278110,0.120515,0.043299,0.002579,0.033066,0.031059,NaN,0.378115

In [16]:
# Handle trade balance

In [17]:
trade=pd.read_excel("Data\\Originais\\cross-section\\EXPORTACAO_E IMPORTACAO_GERAL_2016-01_2019-12.xlsx")
trade.columns=["UF","Export_2019","Import_2019","Export_2018","Import_2018","Export_2017","Import_2017","Export_2016","Import_2016"]

In [18]:
#dados= yf.Ticker("USDBRL=X")
#dados = pd.DataFrame(yf.download("USDBRL=X", start="2016-01-01", end="2020-01-01")["Close"])

In [19]:
#dolarMedio = dados["USDBRL=X"].mean()
dolarMedio= 3.5669393161168466
print(dolarMedio)

3.5669393161168466

In [20]:
# Ajust value
trade["Export_2016"]=trade["Export_2016"]/1000*dolarMedio
trade["Export_2017"]=trade["Export_2017"]/1000*dolarMedio
trade["Export_2018"]=trade["Export_2018"]/1000*dolarMedio
trade["Export_2019"]=trade["Export_2019"]/1000*dolarMedio
trade["Import_2016"]=trade["Import_2016"]/1000*dolarMedio
trade["Import_2017"]=trade["Import_2017"]/1000*dolarMedio
trade["Import_2018"]=trade["Import_2018"]/1000*dolarMedio
trade["Import_2019"]=trade["Import_2019"]/1000*dolarMedio
trade.replace(estados,inplace=True)
trade = trade[trade["UF"].isin(estados.values())]
trade = pd.merge(trade,PIB,on="UF",how="outer")
trade = trade[trade["UF"].isin(estados.values())]

In [21]:
# Obtain percents
trade["export_liq_pib"]=(
((trade["Export_2016"]-trade["Import_2016"])/trade["2016_PIB"])+
((trade["Export_2017"]-trade["Import_2017"])/trade["2017_PIB"])+
((trade["Export_2018"]-trade["Import_2018"])/trade["2018_PIB"])+
((trade["Export_2019"]-trade["Import_2019"])/trade["2019_PIB"]))/4

In [22]:
trade.columns

Index(['UF', 'Export_2019', 'Import_2019', 'Export_2018', 'Import_2018',
       'Export_2017', 'Import_2017', 'Export_2016', 'Import_2016', '2016_PIB',
       '2017_PIB', '2018_PIB', '2019_PIB', 'export_liq_pib'],
      dtype='object')

In [23]:
trade.drop(columns=['Export_2019', 'Import_2019', 'Export_2018', 'Import_2018',
       'Export_2017', 'Import_2017', 'Export_2016', 'Import_2016', 
       '2016_PIB',
       '2017_PIB',
       '2018_PIB', 
       '2019_PIB'],inplace=True)

In [24]:
main = pd.merge(main, trade, on="UF", how="outer")
main.dropna(inplace=True)
main.reset_index(inplace=True,drop=True)

In [25]:
# Handle with demografy data

In [26]:
dados = pd.read_excel("Data\\Originais\\cross-section\\Tabela 4714.xlsx", sheet_name="Densidade demográfica; 2022", skipfooter=1, skiprows=3)
dados.columns = ["UF", "DensidadeDemografica"]
dados = dados[dados["UF"].isin(list(estados.keys()))]
dados.replace(estados,inplace=True)
dados.reset_index(drop=True,inplace=True)
main = pd.merge(main,dados,on="UF",how="outer")

In [27]:
main

,UF,Bem,Agro,Construcao,Extrativa,Transformacao,financas,DivPub,state_expenditure_pib,export_liq_pib,DensidadeDemografica
0,BA,0.182795,0.062287,0.048139,0.008623,0.108648,0.032481,0.142222,0.254504,0.019298,25.04
1,CE,0.207890,0.045608,0.045136,0.002286,0.076003,0.038262,0.142414,0.244484,-0.026395,59.07
2,ES,0.140967,0.035214,0.037281,0.075188,0.088425,0.035289,0.092903,0.186427,0.121065,83.21
3,GO,0.151541,0.103233,0.050037,0.005501,0.103399,0.040765,0.171402,0.199115,0.109867,20.74
4,MG,0.152516,0.049225,0.042647,0.036676,0.122159,0.040309,0.331060,0.263899,0.160990,35.02
5,PA,0.199424,0.102179,0.044781,0.130209,0.040579,0.020320,0.041459,0.231832,0.506031,6.52
6,PE,0.211006,0.036080,0.037701,0.000655,0.107437,0.035859,0.140269,0.287995,-0.133598,92.37
7,PR,0.121281,0.081074,0.038991,0.001251,0.138013,0.039795,0.093848,0.186695,0.052208,57.42
8,RJ,0.176012,0.004239,0.034841,0.067150,0.055101,0.044472,0.340555,0.148103,0.044737,366.97
9,RS,0.126015,0.080283,0.036419,0.000960,0.139078,0.049479,0.306503,0.239152,0.100015,38.63
10,SC,0.119855,0.050643,0.041845,0.002349,0.164238,0.033113,0.134981,0.138033,-0.106431,79.50
11,SP,0.081014,0.015795,0.032552,0.004192,0.125855,0.107320,0.230234,0.168480,-0.028297,178.92

In [28]:
# Merge IRF

In [29]:
dados = pd.read_excel("Data\\Resultados\\IRF_Cumulative_stata.xlsx")

In [30]:
dados

    UF   IRF3CUM   IRF6CUM   IRF9CUM  IRF12CUM  IRF24CUM
0   BA -0.011139 -0.021188 -0.027721 -0.030549 -0.019741
1   CE -0.011031 -0.021672 -0.028755 -0.031594 -0.016637
2   ES -0.017183 -0.039016 -0.058165 -0.072695 -0.091852
3   GO -0.004855 -0.008655 -0.011180 -0.012422 -0.004922
4   MG -0.008130 -0.020781 -0.030333 -0.036667 -0.040102
5   PA  0.003599  0.002368  0.000676 -0.000369  0.005132
6   PE -0.001766 -0.001351 -0.000074  0.002385  0.022610
7   PR -0.003978 -0.014130 -0.021704 -0.024987 -0.008771
8   RJ -0.004062 -0.007889 -0.010978 -0.012856 -0.007156
9   RS -0.004816 -0.011292 -0.014438 -0.013878  0.008876
10  SC -0.006338 -0.010663 -0.011828 -0.009813  0.016269
11  SP -0.004449 -0.011365 -0.016592 -0.019036 -0.006300

In [31]:
# Merge final
main = pd.merge(main,dados,on="UF",how="outer")

In [32]:
main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   UF                     12 non-null     object
 1   Bem                    12 non-null     float64
 2   Agro                   12 non-null     float64
 3   Construcao             12 non-null     float64
 4   Extrativa              12 non-null     float64
 5   Transformacao          12 non-null     float64
 6   financas               12 non-null     float64
 7   DivPub                 12 non-null     float64
 8   state_expenditure_pib  12 non-null     float64
 9   export_liq_pib         12 non-null     float64
 10  DensidadeDemografica   12 non-null     float64
 11  IRF3CUM                12 non-null     float64
 12  IRF6CUM                12 non-null     float64
 13  IRF9CUM                12 non-null     float64
 14  IRF12CUM               12 non-null     float64
 15  IRF24CUM               12 non-null     float64
dtypes: float64(15), object(1)
memory usage: 1.6+ KB

In [33]:
main

,UF,Bem,Agro,Construcao,Extrativa,Transformacao,financas,DivPub,state_expenditure_pib,export_liq_pib,DensidadeDemografica,IRF3CUM,IRF6CUM,IRF9CUM,IRF12CUM,IRF24CUM
0,BA,0.182795,0.062287,0.048139,0.008623,0.108648,0.032481,0.142222,0.254504,0.019298,25.04,-0.011139,-0.021188,-0.027721,-0.030549,-0.019741
1,CE,0.207890,0.045608,0.045136,0.002286,0.076003,0.038262,0.142414,0.244484,-0.026395,59.07,-0.011031,-0.021672,-0.028755,-0.031594,-0.016637
2,ES,0.140967,0.035214,0.037281,0.075188,0.088425,0.035289,0.092903,0.186427,0.121065,83.21,-0.017183,-0.039016,-0.058165,-0.072695,-0.091852
3,GO,0.151541,0.103233,0.050037,0.005501,0.103399,0.040765,0.171402,0.199115,0.109867,20.74,-0.004855,-0.008655,-0.011180,-0.012422,-0.004922
4,MG,0.152516,0.049225,0.042647,0.036676,0.122159,0.040309,0.331060,0.263899,0.160990,35.02,-0.008130,-0.020781,-0.030333,-0.036667,-0.040102
5,PA,0.199424,0.102179,0.044781,0.130209,0.040579,0.020320,0.041459,0.231832,0.506031,6.52,0.003599,0.002368,0.000676,-0.000369,0.005132
6,PE,0.211006,0.036080,0.037701,0.000655,0.107437,0.035859,0.140269,0.287995,-0.133598,92.37,-0.001766,-0.001351,-0.000074,0.002385,0.022610
7,PR,0.121281,0.081074,0.038991,0.001251,0.138013,0.039795,0.093848,0.186695,0.052208,57.42,-0.003978,-0.014130,-0.021704,-0.024987,-0.008771
8,RJ,0.176012,0.004239,0.034841,0.067150,0.055101,0.044472,0.340555,0.148103,0.044737,366.97,-0.004062,-0.007889,-0.010978,-0.012856,-0.007156
9,RS,0.126015,0.080283,0.036419,0.000960,0.139078,0.049479,0.306503,0.239152,0.100015,38.63,-0.004816,-0.011292,-0.014438,-0.013878,0.008876
10,SC,0.119855,0.050643,0.041845,0.002349,0.164238,0.033113,0.134981,0.138033,-0.106431,79.50,-0.006338,-0.010663,-0.011828,-0.009813,0.016269
11,SP,0.081014,0.015795,0.032552,0.004192,0.125855,0.107320,0.230234,0.168480,-0.028297,178.92,-0.004449,-0.011365,-0.016592,-0.019036,-0.006300

In [34]:
main.to_excel("Data\\Resultados\\final_base.xlsx")